version: '3'
services:
  app:
    container_name: tool-in-docker
    # build:
    #   context: build
    #   args:
    #     username: peccu
    #     homedir: /mnt/c/Users
    image: peccu/tool-in-docker:ansible
    environment:
      - TOOLTYPE=tool
      # X11
      - DISPLAY
      # Wayland
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR
      # PulseAudio
      - PULSE_SERVER
      # # Docker in Docker : this is default sock
      # - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /:/mnt/host
      # for mount local path into container
      - ~:$HOME
      # for chezmoi cd
      - /run/user/1000:/run/user/1000
      # tmux UID is defined in .env file
      - /tmp/tmux-${UID}:/tmp/tmux-${UID}
      - /clip:/clip
      - /open:/open
      # X11
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Wayland and PulseAudio
      - /mnt/wslg:/mnt/wslg
      # vGPU
      - /dev/dxg:/dev/dxg
      - /usr/lib/wsl:/usr/lib/wsl
      # Docker in Docker
      # test by curl --unix-socket /var/run/docker.sock http://localhost/version
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    # working_dir: /root
    # entrypoint: tail -f /dev/null
    # entrypoint: sleep infinity
    # stop_signal: SIGKILL
    restart: always
    # networks:
    #   - gitea
    #   - default
  cron:
    profiles: ["cron"]
    build: build_cron
    restart: always
    volumes:
      - ~:/root
      # - ./crontask/cron.daily:/etc/cron.daily:ro
      # - ./crontask/cron.hourly:/etc/cron.hourly:ro
      - ./crontask/cron.monthly:/etc/cron.monthly:ro
      # - ./crontask/cron.weekly:/etc/cron.weekly:ro
    # working_dir: /root
    # entrypoint: tail -f /dev/null
    # command: crond -f -l 8
    stop_signal: SIGKILL

# networks:
#   gitea:
#     external: true
#     name: gitea
